# Clase 9

#### **Contenido**
- Dudas ejercicio final
- Mínima introducción a Numpy
- If con verdadero, con lista vacía, con string vacio, con DataFrame Vacio, con 0
- List comprehension (Dict comprehension)
- Pandas Repaso
  - Como crear una columna
  - Como eliminar una columna
  - Como eliminar una fila
  - Como seleccionar una columna
  - Como seleccionar una fila
  - Como asignar un valor a una columna entera
  - Como asignar un valor dinamico a una columna
- Visualización con plotly (Desde Pandas 🐼)
- Iniciar POO

#### Temas de estudio
- Qué es un algoritmo de ordenamiento?
- Qué es un algoritmo de búsqueda?
- Cuales son los paradigmas de la programación?

#### Links

- [Numpy](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [11]:
!pip install numpy

### Conceptos claves de POO (OOP - Object Oriented Programming)

#### Objetos y Clases:
Plano (Clase) y Edificio (Objeto)   
    Ejemplo: Clase Persona:  
        Atributos:  
        - Nombre  
        - Edad  
        - Estatura  
        - Peso  
        Métodos:  
        - Hablar  
        - Caminar  
        - Comer  

#### Encapsulamiento:
Cápsula que autocontiene y protege su contenido.   
    Ejemplo: Clase Persona nadie puede tener sus atributos ni métodos, excepto
    la clase persona.

#### Herencia:
Relación de padre e hijo.   
    Ejemplo: Clase Persona es el padre.  
    Clases hijos son las Clase Estudiante, Clase Profesor, Clase Conductor.

#### Polimorfismo:
Demuestra que un objeto puede comportarse de diferentes maneras. El polimorfismo se puede ver
entre objetos, entre clases y entre padres e hijos.
    Ejemplo: Clase Forma, puede tener varias Clases hijas como Circulo o Cuadrado,
    ambos con el método calcular_area, pero cada uno lo hace de manera diferente.

In [ ]:
import math as m

In [ ]:
class Persona:
    def __init__(self, nombre, edad, estatura, peso):
        self.nombre = nombre
        self.edad = edad
        self.estatura = estatura
        self.peso = peso

    def hablar(self):
        print("Hola")

    def caminar(self):
        print("Caminando ...")

    def comer(self):
        print("Comiendo ...")

In [5]:
lista1 = [1, 2, 3]
print(lista1)
print(lista1[0])
print(lista1[::-1])
print(lista1.reverse())
print(lista1)

[1, 2, 3]
1
[3, 2, 1]
None
[3, 2, 1]


In [10]:
print(lista1)
print(lista1[:2]) # Slicing de listas

[3, 2, 1]
[3, 2]


In [14]:
!python --version

Python 3.10.12


In [12]:
import numpy as np

In [ ]:
# Python para ciencia de datos
# Pandas, Numpy, Plotly
# statsmodels, scikitlearn
# Big Data - PySpark - Spark

# Machine Learning
# Tensorflow - Pytorch

In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [17]:
print(np.ones([2, 3]))

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(np.zeros([3, 2]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# JavaScript (React, Vue, Angular, Next) - Frontend
# TypeScript

# Lo que pasa detras de las paginas - Backend
# Para el backend tambien es famoso python
# FastAPI - Pydantic
# Go, Rust
"""
Hay librerias que me permiten hacer demos en paginas web
dash-plotly , django, streamlit
"""

In [22]:
lista2 = [1, 2, 3]
for i in range(1, len(lista2)):
  print(lista2[i])

2
3


In [24]:
# Forma de los condicionales
lista3 = []

if len(lista3) == 0:
  print("lista vacia")
else:
  print("lista tiene elementos")

if lista3: # Verdadero cuando si tiene elementos Falso cuando no tiene elementos
  print("lista tiene elementos")
else:
  print("lista vacia")

lista vacia
lista vacia


In [25]:
documento = ""

# 1. len porque los strings tambien tienen longitud, len(documento) == 0
# 2. documento == ""
if documento:
  print("el documento tiene palabras")
else:
  print("Esta vacio")

Esta vacio


In [ ]:
# Está comparacion vacia, tambien se puede hacer con
# Dict, Set, DataFrame

In [ ]:
# Comprension - en listas o diccionarios
# La compresion, normalmente se hace para simplificar codigo
# Para ahorrar lineas, para volver un proceso mas eficiente
# Sin embargo, SIN la compresion el codigo funciona igual

In [26]:
# List comprehension
lista4 = [1, 2, 3, 4, 5]
lista5 = [] # Debo añadir solo los elementos impares de lista4 a lista5
for number in lista4:
  if (number % 2) == 1:
    lista5.append(number)
print(lista4)
print(lista5)

[1, 2, 3, 4, 5]
[1, 3, 5]


In [28]:
# 1. Me robo la parte del for
# 2. Pongo la condicion despues (Si hay condicion)
# 3. Añado el iterador antes
lista5 = [number for number in lista4 if (number % 2) == 1]
lista6 = [-1 for number in lista4 if (number % 2) == 1]
print(lista4)
print(lista5)
print(lista6)

# Restricciones, debe estar dentro de corchetes
# no siempre debe tener condiciones
# Solo se puede hacer con FOR
# Sirve para velocidad, tidyness, sintetizar

[1, 2, 3, 4, 5]
[1, 3, 5]
[-1, -1, -1]


In [29]:
lista7 = ["una", "palabra", "dos", "okey", "nuevo"]
lista8 = [] # Voy a añadir las palabras impares de longitud
for word in lista7:
  if (len(word) % 2) == 1:
    lista8.append(word[::-1]) # aca estoy añadiendo la palabra al reves
print(lista7)
print(lista8)

['una', 'palabra', 'dos', 'okey', 'nuevo']
['anu', 'arbalap', 'sod', 'oveun']


In [33]:
lista8 = [word[::-1] for word in lista7 if (len(word) % 2) == 1]
print(lista8)

lista9 = [word[::-1] if (len(word) % 2) == 1  else word for word in lista7]
print(lista9)
# Las comprensiones de lista, eliminan los dos puntos y el append
lista9 = []
for word in lista7:
  if (len(word) % 2) == 1:
    lista9.append(word[::-1])
  else:
    lista9.append(word)
# Puede tener varios condicionales
# Puede tener varios sub for
# Puede añadir varias cosas

['anu', 'arbalap', 'sod', 'oveun']
['anu', 'arbalap', 'sod', 'okey', 'oveun']


In [48]:
from random import randint
lista10 = [randint(10, 20) for i in range(5)]
print(lista10)

for index, element in enumerate(lista10):
  print(f"Iteracion {index}")
  print(f"Elemento {element}")

for conjunto in enumerate(lista10):
  print(f"Iteracion {conjunto[0]}")
  print(f"Elemento {conjunto[1]}")

[14, 17, 15, 17, 18]
Iteracion 0
Elemento 14
Iteracion 1
Elemento 17
Iteracion 2
Elemento 15
Iteracion 3
Elemento 17
Iteracion 4
Elemento 18
Iteracion 0
Elemento 14
Iteracion 1
Elemento 17
Iteracion 2
Elemento 15
Iteracion 3
Elemento 17
Iteracion 4
Elemento 18


In [54]:
tupla1 = (1, 3) # Inmutable
# tupla1 = (3 ,5)
# tupla1[0] = 4 # AQUI SALE UN ERROR

lista1 = [1, 3]
lista1[0] = 4
print(lista1)

[4, 3]


In [56]:
lista11 = [10, 20, 30, 40]
lista12 = [conjunto for conjunto in enumerate(lista11)]
print(lista12)

[(0, 10), (1, 20), (2, 30), (3, 40)]


In [59]:
meses = range(12)
nombres_meses = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre",
    "diciembre"
]
diccionario_nombres = {}
for n in meses:
  diccionario_nombres[nombres_meses[n]] = n + 1
print(diccionario_nombres)

{'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4, 'mayo': 5, 'junio': 6, 'julio': 7, 'agosto': 8, 'septiembre': 9, 'octubre': 10, 'noviembre': 11, 'diciembre': 12}


In [60]:
# Dict comprehension
diccionario_nombres = {nombres_meses[n]: n + 1 for n in meses}
print(diccionario_nombres)

{'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4, 'mayo': 5, 'junio': 6, 'julio': 7, 'agosto': 8, 'septiembre': 9, 'octubre': 10, 'noviembre': 11, 'diciembre': 12}


In [69]:
nombres_meses = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre",
    "diciembre"
]
meses_vocales = [] # Crear una nueva lista, que tenga
# solo los meses que empiezan con una vocal
# 1. if m[0] == "a" or m[0] == "e" or ...
# 2. if m[0] in "aeiou"

for m in nombres_meses:
  # print(m[0])
  if m[0] in "aeiou":
    meses_vocales.append(m)
  # print(meses_vocales)

meses_vocales_lc = [m for m in nombres_meses if m[0] in "aeiou"]
# print(meses_vocales)
# print(meses_vocales_lc)

# Crear un diccionario, en el cual se le añadan los numeros correspodientes
# A los meses que tengan una vocal al inicio, el resto de meses no debe ser
# añadido al diccionario
meses = range(12)
nombres_meses = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre",
    "diciembre"
]
diccionario_vocales = {}
for n in meses:
  if nombres_meses[n][0] in "aeiou":
    diccionario_vocales[nombres_meses[n]] = n + 1

# Debo resumir en dict comprehension
diccionario_vocales_lc = {nombres_meses[n]: n + 1 for n in meses
                          if nombres_meses[n][0] in "aeiou"}

print(diccionario_vocales)
print(diccionario_vocales_lc)

{'enero': 1, 'abril': 4, 'agosto': 8, 'octubre': 10}
{'enero': 1, 'abril': 4, 'agosto': 8, 'octubre': 10}


In [70]:
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_train.csv")
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  


In [71]:
print(df.columns)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')


In [72]:
print(df.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.00000

In [73]:
print(df["median_house_value"])

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64


In [74]:
df["median_house_value_agg"] = df["median_house_value"] + 10000
print(df["median_house_value_agg"])

0         76900.0
1         90100.0
2         95700.0
3         83400.0
4         75500.0
           ...   
16995    121400.0
16996     89000.0
16997    113600.0
16998     95800.0
16999    104600.0
Name: median_house_value_agg, Length: 17000, dtype: float64


In [ ]:
# POO - OOP Object oriented programming
# class es una nueva palabra reservada


class Ruleta:
  # Atributo Cuales numeros pueden salir
  # Atributo Cuanto pago por cada numero
  # Atributo Cuanta plata tengo
  # Metodo - Girar
  # Metodo - Pagar
  # Metodo - Jugar de nuevo

# Las clases tienen metodos y tienen atributos
# Las funciones adentro de las clases, se llaman metodos

# Yo creo metodos para hacer cosas con el objeto
# yo creo los atributos para describir el objeto

In [75]:
class Persona:
    def __init__(self, nombre, edad, estatura, peso): # Metodo inicializar
        self.nombre = nombre
        self.edad = edad
        self.estatura = estatura
        self.peso = peso

    def hablar(self):
        print("Hola")

    def caminar(self):
        print("Caminando ...")

    def comer(self):
        print("Comiendo ...")

mateo = Persona("nombre", 19, 178, 80)
print(mateo)